theme: jekyll-theme-minimal
<img src="sam.jpg" style="width:100%" alt="Avatar">
title: Sam Shwadlenak Trizza
author: sam trizza
email: sam-trizza@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  Hello! Welcome to my resume site.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
